routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', ['as' => 'home_tree', 'uses' => 'TreePageController@index' ] );
Route::get('/treedata/', ['as' => 'tree_data', 'uses' => 'TreePageController@data',]);

Route::post('/movenode/', ['as' => 'move_node', 'uses' => 'TreePageController@move',]);
Auth::routes();

Route::get('/list-in-table/', ['as' => 'tablelist', 'uses' => 'TablePageController@index', 'middleware' => 'auth']);
Route::post('/list-in-table/', ['as' => 'workers_list', 'uses' => 'TablePageController@ajaxIndex']);

Route::resource('appointments', 'AppointmentController')->middleware('auth');
Route::post('tabledata', ['as' => 'tabledata', 'uses' => 'AppointmentController@ajaxIndex',]);

Route::post('bosses', [ 'uses' => 'SearchController@getBossList',]);
Route::post('peoples', [ 'uses' => 'SearchController@getPeoplesList',]);
Route::post('positions', [ 'uses' => 'SearchController@getPositionsList',]);

resources/views/page/create.blade.php
@extends('app')

@section('title','Создание нового назначения')

@section('content')
    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="container-fluid" id="app-container">
        <p class="text-info">*все поля являются обязательными для заполнения</p>
        {!! Form::open(['class'=>'form-horizontal', 'route' => 'appointments.store','files'=>'true']) !!}

        <div class="form-group">
            {!! Form::label('inputPeople', 'Сотрудник',['class'=>'col-sm-2']) !!}
            <div class="col-sm-4 search-field">
                {!! Form::text('', null, ['class' => 'form-control search-input', 'id'=>'inputPeople','autocomplete'=>'off', 'required' => 'required'])!!}
                {!! Form::hidden('people', null, ['id'=>'inputPeopleField', 'required' => 'required'])!!}
                <div class="search_data hidden" id="search_people"></div>
            </div>
        </div>

        <div class="form-group people-group hidden">
            {!! Form::label('inputFName', 'Имя',['class'=>'col-sm-2']) !!}
            <div class="col-sm-3">
                {!! Form::text('first_name', null, ['class' => 'form-control', 'id'=>'inputFName'])!!}
            </div>
        </div>
        <div class="form-group people-group hidden">
            {!! Form::label('inputLName', 'Фамилия',['class'=>'col-sm-2']) !!}
            <div class="col-sm-3">
                {!! Form::text('last_name',  null , ['class' => 'form-control', 'id'=>'inputLName'])!!}
            </div>
        </div>
        <div class="form-group people-group hidden">
            {!! Form::label('inputSex', 'Пол',['class'=>'col-sm-2']) !!}
            <div class="col-sm-2">
                {!! Form::select('sex', ['1' => 'М', '0' => 'Ж'], 1, ['class' => 'form-control','id' => 'inputSex'])!!}
            </div>
        </div>
        <div class="form-group people-group hidden">
            {!! Form::label('inputPhoto', 'Фото',['class'=>'col-sm-2']) !!}
            <div class="col-sm-3">
                <img src="{{asset('img/images.png')}}" id="image_show" />
                {!! Form::file('avatar_image',['id'=>'image_input']) !!}
                {!! Form::hidden('avatar_changed',0,['id'=>'image_fl']) !!}
            </div>
        </div>

        <div class="form-group">
            {!! Form::label('inputPosition', 'Должность',['class'=>'col-sm-2']) !!}
            <div class="col-sm-4 search-field">
                {!! Form::text('', null, ['class' => 'form-control search-input','autocomplete'=>'off', 'id'=>'inputPosition', 'required' => 'required'])!!}
                {!! Form::hidden('position', null, ['id'=>'inputPositionField', 'required' => 'required'])!!}
                <div class="search_data hidden" id="search_position"></div>
            </div>
        </div>

        <div class="form-group position-group hidden">
            {!! Form::label('inputSubdiv', 'Подразделение',['class'=>'col-sm-2']) !!}
            <div class="col-sm-3">
                {!! Form::text('subdiv', session('lar_test_subdiv'), ['class' => 'form-control', 'id'=>'inputSubdiv'])!!}
            </div>
        </div>
        <div class="form-group position-group hidden">
            {!! Form::label('inputPos', 'Должность',['class'=>'col-sm-2']) !!}
            <div class="col-sm-3">
                {!! Form::text('pos', session('lar_test_pos'), ['class' => 'form-control', 'id'=>'inputPos'])!!}
            </div>
        </div>

        <div class="form-group">
            {!! Form::label('inputType', 'Тип назначения',['class'=>'col-sm-2']) !!}
            <div class="col-sm-2">
                {!! Form::select('type', $types_arr, 1, ['class' => 'form-control','id' => 'inputType'])!!}
            </div>
        </div>

        <div class="form-group">
            {!! Form::label('inputBoss', 'Начальник',['class'=>'col-sm-2']) !!}
            <div class="col-sm-4 search-field">
                {!! Form::text('boss_text', null, ['class' => 'form-control search-input','autocomplete'=>'off', 'id'=>'inputBoss'])!!}
                {!! Form::hidden('boss', null, ['id'=>'inputBossField', 'required' => 'required'])!!}
                <div class="search_data hidden" id="search_boss"></div>
            </div>
        </div>

        <div class="form-group">
            {!! Form::label('inputDate', 'Дата назначения',['class'=>'col-sm-2']) !!}
            <div class="col-sm-3">
                {!! Form::date('date', date('Y-m-d'), ['class' => 'form-control', 'id'=>'inputDate', 'required' => 'required'])!!}
            </div>
        </div>

        <div class="form-group">
            {!! Form::label('inputSalary', 'Зар. плата',['class'=>'col-sm-2']) !!}
            <div class="col-sm-3">
                {!! Form::number('salary', null, ['class' => 'form-control', 'id'=>'inputSalary', 'required' => 'required'])!!}
            </div>
        </div>
        <div class="buttons-goup">
            <div class="col-sm-3 col-sm-offset-2">
                {!! Form::submit('Сохранить', ['class' => 'btn btn-primary'])!!}
            </div>
        </div>
        {!! Form::close() !!}
    </div>
@endsection

resources/views/page/edit.blade.php
@extends('app')

@section('title','Редактирование назначения #'.$item->appointment_id)

@section('content')
    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="container-fluid" id="app-container">
        <p class="text-info">*все поля являются обязательными для заполнения</p>
        {!! Form::open(['class'=>'form-horizontal', 'route' => ['appointments.update',$item->appointment_id], 'method' => 'put','files'=>'true']) !!}

        <div class="form-group">
            {!! Form::label('inputPeople', 'Сотрудник',['class'=>'col-sm-2']) !!}
            <div class="col-sm-4 search-field">
                {!! Form::text('', $people_string, ['class' => 'form-control search-input','autocomplete'=>'off', 'id'=>'inputPeople', 'required' => 'required'])!!}
                {!! Form::hidden('people', $item->people_id, ['id'=>'inputPeopleField', 'required' => 'required'])!!}
                <div class="search_data hidden" id="search_people"></div>
            </div>
        </div>

        <div class="form-group people-group hidden">
            {!! Form::label('inputFName', 'Имя',['class'=>'col-sm-2']) !!}
            <div class="col-sm-3">
                {!! Form::text('first_name', null, ['class' => 'form-control', 'id'=>'inputFName'])!!}
            </div>
        </div>
        <div class="form-group people-group hidden">
            {!! Form::label('inputLName', 'Фамилия',['class'=>'col-sm-2']) !!}
            <div class="col-sm-3">
                {!! Form::text('last_name',  null , ['class' => 'form-control', 'id'=>'inputLName'])!!}
            </div>
        </div>
        <div class="form-group people-group hidden">
            {!! Form::label('inputSex', 'Пол',['class'=>'col-sm-2']) !!}
            <div class="col-sm-2">
                {!! Form::select('sex', ['1' => 'М', '0' => 'Ж'], 1, ['class' => 'form-control','id' => 'inputSex'])!!}
            </div>
        </div>
        <div class="form-group people-group hidden">
            {!! Form::label('inputPhoto', 'Фото',['class'=>'col-sm-2']) !!}
            <div class="col-sm-3">
                <img src="{{asset('img/images.png')}}" id="image_show" />
                {!! Form::file('avatar_image',['id'=>'image_input']) !!}
                {!! Form::hidden('avatar_changed',0,['id'=>'image_fl']) !!}
            </div>
        </div>
        <div class="form-group">
            {!! Form::label('inputPosition', 'Должность',['class'=>'col-sm-2']) !!}
            <div class="col-sm-4 search-field">
                {!! Form::text('', $position_string, ['class' => 'form-control search-input','autocomplete'=>'off', 'id'=>'inputPosition', 'required' => 'required'])!!}
                {!! Form::hidden('position', $item->position_id, ['id'=>'inputPositionField', 'required' => 'required'])!!}
                <div class="search_data hidden" id="search_position"></div>
            </div>
        </div>

        <div class="form-group position-group hidden">
            {!! Form::label('inputSubdiv', 'Подразделение',['class'=>'col-sm-2']) !!}
            <div class="col-sm-3">
                {!! Form::text('subdiv', session('lar_test_subdiv'), ['class' => 'form-control', 'id'=>'inputSubdiv'])!!}
            </div>
        </div>
        <div class="form-group position-group hidden">
            {!! Form::label('inputPos', 'Должность',['class'=>'col-sm-2']) !!}
            <div class="col-sm-3">
                {!! Form::text('pos', session('lar_test_pos'), ['class' => 'form-control', 'id'=>'inputPos'])!!}
            </div>
        </div>

        <div class="form-group">
            {!! Form::label('inputType', 'Тип назначения',['class'=>'col-sm-2']) !!}
            <div class="col-sm-2">
                {!! Form::select('type', $types_arr, $item->appointment_type_id, ['class' => 'form-control','id' => 'inputType'])!!}
            </div>
        </div>

        <div class="form-group">
            {!! Form::label('inputBoss', 'Начальник',['class'=>'col-sm-2']) !!}
            <div class="col-sm-4 search-field">
                {!! Form::text('boss_text', $boss_string, ['class' => 'form-control search-input','autocomplete'=>'off', 'id'=>'inputBoss'])!!}
                {!! Form::hidden('boss', $item->appointment_boss_id, ['id'=>'inputBossField', 'required' => 'required'])!!}
                <div class="search_data hidden" id="search_boss"></div>
            </div>
        </div>

        <div class="form-group">
            {!! Form::label('inputDate', 'Дата назначения',['class'=>'col-sm-2']) !!}
            <div class="col-sm-3">
                {!! Form::date('date', $item->date, ['class' => 'form-control', 'id'=>'inputDate', 'required' => 'required'])!!}
            </div>
        </div>

        <div class="form-group">
            {!! Form::label('inputSalary', 'Зар. плата',['class'=>'col-sm-2']) !!}
            <div class="col-sm-3">
                {!! Form::number('salary', $item->salary, ['class' => 'form-control', 'id'=>'inputSalary', 'required' => 'required'])!!}
            </div>
        </div>

        <div class="buttons-goup">
            <div class="col-sm-3 col-sm-offset-2">
                {!! Form::submit('Сохранить', ['class' => 'btn btn-primary'])!!}
            </div>
        </div>
        {!! Form::close() !!}
    </div>
@endsection

resources/views/page/index.blade.php
@extends('app')

@section('title','Список назначений работников')

@section('content')
<div class="container">
    <p>
        <a href="{{ route('appointments.create') }}" class="btn btn-primary">Добавить запись</a>
    </p>
</div>
<div  id="app-container">
    @include('page.table')
</div>
@endsection

resources/views/page/show.blade.php
@extends('app')

@section('title','Просмотр назначения #'.$item->appointment_id)

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2"><p><strong>Фото</strong></p></div>
            <div><p>
                @if($people->avatar_image_id)
                    <img src="{{ asset($people->avatar_image->url('thumb')) }}">
                @else
                        <img src="{{asset('img/images.png')}}" />
                @endif
            </p></div>
        </div>
        <div class="row">
            <div class="col-sm-2"><p><strong>Имя</strong></p></div>
            <div><p>{{$people->first_name}}</p></div>
        </div>
        <div class="row">
            <div class="col-sm-2"><p><strong>Фамилия</strong></p></div>
            <div><p>{{$people->last_name}}</p></div>
        </div>
        <div class="row">
            <div class="col-sm-2"><p><strong>Пол</strong></p></div>
            <div><p>{{ ($people->isMale) ? 'М' : 'Ж' }}</p></div>
        </div>
        <div class="row">
            <div class="col-sm-2"><p><strong>Подразделение</strong></p></div>
            <div><p>{{$position->subdivision_name}}</p></div>
        </div>
        <div class="row">
            <div class="col-sm-2"><p><strong>Должность</strong></p></div>
            <div><p>{{$position->position_name}}</p></div>
        </div>
        <div class="row">
            <div class="col-sm-2"><p><strong>Тип назначения</strong></p></div>
            <div><p>{{ ($item->appointment_type_id) ? 'прием' : (($item->appointment_type_id == 0)? 'перевод' : 'увольнение') }}</p></div>
        </div>
        <div class="row">
            <div class="col-sm-2"><p><strong>Дата назначения</strong></p></div>
            <div><p>{{ Carbon\Carbon::parse($item->date)->format('d.m.Y') }}</p></div>
        </div>
        <div class="row">
            <div class="col-sm-2"><p><strong>Зар. плата</strong></p></div>
            <div><p>{{ $item->salary }}</p></div>
        </div>
        @if($boss)
            <div class="row">
                <div class="col-sm-2"><p><strong>Начальник</strong></p></div>
                <div><p><a href="{{ $boss_url }}">{{ $boss }}</a></p></div>
            </div>
        @endif
        <div class="row">
            <a href="{{route('appointments.edit',['appointment' => $item->appointment_id] )}}" class=" col-sm-offset-2 btn btn-primary">Редактировать</a>
            {!! Form::open(['route' => ['appointments.destroy', $item->appointment_id], 'method' => 'delete', 'class' => 'delete_form']) !!}
            {!! Form::button('Удалить', ['class' => 'btn btn-default del-row'])!!}
            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/page/table.blade.php
<div class="container-fluid" id="ajax-container">
  @if(count($data) > 0)
  <table class="table table-hover">
    <thead>
    <tr class="info">
        @foreach($order_arr as $key => $row)
            <td>
                {{ $row['name'] }}
                @if($key != 'photo')
                    <a href="{{ route('tabledata') }}" data-orderby = '{{ $key }}'  data-order = '{{$row['order']}}'><i class="fa {{$row['order_class']}}"></i></a>
                @endif
            </td>
        @endforeach
        <td></td>
    </tr>
    </thead>
    <tbody>
    <?php ?>
    @foreach($data as $key => $employee)
      <tr>
          <td>{{ $employee->appointment_id }}</td>
          <td>
              @if($employee->avatar_image_id)
                  <?php $image =Image::find($employee->avatar_image_id);  ?>
                  <a href="{{ $image->original_file_name}}" target="_blank">
                    <img src="{{ asset($image->url('tiny')) }}">
                  </a>
              @else
                  <img src="{{asset('img/images.png')}}" />
              @endif
          </td>
          <td>{{ $employee->first_name }}</td>
          <td>{{ $employee->last_name }}</td>
          <td>{{ ($employee->isMale) ? 'М' : 'Ж' }}</td>
          <td>{{ $employee->subdivision_name }}</td>
          <td>{{ $employee->position_name }}</td>
          <td>{{ $employee->type_description }}</td>
          <td>{{ Carbon\Carbon::parse($employee->date)->format('d.m.Y') }}</td>
          <td>{{ $employee->salary }}</td>
          <td>
              <a class="fa fa fa-eye" title="просмотр" aria-hidden="true" href="{{route('appointments.show',['appointment' => $employee->appointment_id] )}}"></a>
              <a class="fa fa-pencil-square-o" title="изменить" aria-hidden="true" href="{{route('appointments.edit',['appointment' => $employee->appointment_id] )}}"></a>
              {!! Form::open(['route' => ['appointments.destroy', $employee->appointment_id], 'method' => 'delete', 'class' => 'delete_form']) !!}
              {!! Form::button('', ['class' => 'fa fa-trash-o del-row', 'title' => 'удалить'])!!}
              {!! Form::close() !!}
          </td>
      </tr>
    @endforeach
    </tbody>
  </table>

    <div >
        {{ $paginate }}
    </div>
  @else
        <p class="bg-primary text-center info-text">По Вашему запросу ничего не найдено</p>
  @endif
</div>