routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', ['as' => 'home_tree', 'uses' => 'TreePageController@index' ] );
Route::get('/treedata/', ['as' => 'tree_data', 'uses' => 'TreePageController@data',]);

Route::post('/movenode/', ['as' => 'move_node', 'uses' => 'TreePageController@move',]);
Auth::routes();

Route::get('/list-in-table/', ['as' => 'tablelist', 'uses' => 'TablePageController@index', 'middleware' => 'auth']);
Route::post('/list-in-table/', ['as' => 'workers_list', 'uses' => 'TablePageController@ajaxIndex']);

Route::resource('appointments', 'AppointmentController')->middleware('auth');
Route::post('tabledata', ['as' => 'tabledata', 'uses' => 'AppointmentController@ajaxIndex',]);

Route::post('bosses', [ 'uses' => 'SearchController@getBossList',]);
Route::post('peoples', [ 'uses' => 'SearchController@getPeoplesList',]);
Route::post('positions', [ 'uses' => 'SearchController@getPositionsList',]);

resources/views/layouts/footer.blade.php
<script src="{{ asset('js/app.js') }}"></script>
<script src="{{ asset('js/scripts.js') }}"></script>
<a href="#top" id="go-top">Вверх</a>

</body>
</html>

resources/views/layouts/header.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="shortcut icon" href="{{ asset('favicon.ico') }}">

    <title>@yield('title')</title>

    <link href="{{ asset('css/app.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('css/style.css') }}" rel="stylesheet" type="text/css">


</head>
<body>
<div id="top"></div>
<div class="container">
    <div class="row">
        <nav class="navbar navbar-default">
            <div class="container-fluid">

                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="{!! route('home_tree') !!}">Список деревом</a></li>
                        <li><a href="{!! route('tablelist') !!}">Сотрудники</a></li>
                        <li><a href="{!! route('appointments.index') !!}">Назначения</a></li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        @guest
                        <li><a href="{{ route('login') }}">Вход</a></li>
                        <li><a href="{{ route('register') }}">Регистрация</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                                    {{ Auth::user()->name }} <i class="fa fa-sort-desc"></i>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                           onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Выход
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" >
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                            @endguest
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
    </div>
</div>

resources/views/layouts/search_res.blade.php
@if($add)
    <p data-code="add">Новый...</p>
@endif
@if(count($data) > 0)
    @foreach($data as $key => $val)
        <p data-code="{{$key}}">{{$val}}</p>
    @endforeach
@endif